---
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  when: devops__systemd | bool

- name: Restart vault
  ansible.builtin.service:
    name: vault
    state: restarted
  when: devops__systemd | bool

- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
  when: devops__systemd | bool
