---
- name: Files | Create the destination directories
  ansible.builtin.file:
    path: "{{ (item.dest is match('/')) | ternary(item.dest, devops__home ~ '/' ~ item.dest) | dirname }}"
    state: directory
    owner: "{{ devops_user }}"
    group: "{{ devops_group }}"
    mode: "0700"
  loop: "{{ devops_provision_files }}"
  loop_control:
    label: "{{ item.dest }}"

- name: Files | Provision the requested files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ (item.dest is match('/')) | ternary(item.dest, devops__home ~ '/' ~ item.dest) }}"
    owner: "{{ devops_user }}"
    group: "{{ devops_group }}"
    mode: "{{ item.mode | default('0600') }}"
  loop: "{{ devops_provision_files }}"
  loop_control:
    label: "{{ item.dest }}"
  no_log: true
